version: '3.8'
services: 
  auth-server: 
    build: 
      context: ./BE/01_AUTH-server
      dockerfile : Dockerfile
    image: auth-server:1.0.0
    expose:
      - 9111
    ports:
      - 9111:9991
    container_name: auth-server

  issuer-server: 
    build: 
      context: ./BE/02_ISSUER-server
      dockerfile : Dockerfile
    image: issuer-server:1.0.0
    expose:
      - 9112
    ports:
      - 9112:9992
    container_name: issuer-server

  holder-server:
    build: 
      context: ./BE/03_HOLDER-server
      dockerfile : Dockerfile
    image: holder-server:1.0.0 
    expose:
      - 9113
    ports:
      - 9113:9993
    container_name: holder-server

  verifier-server:
    build: 
      context: ./BE/04_VERIFIER-server
      dockerfile : Dockerfile 
    image: verifier-server:1.0.0
    expose:
      - 9114
    ports:
      - 9114:9994
    container_name: verifier-server

  react-nginx-app:
    stdin_open: true
    build:
      context: ./FE/client
      dockerfile: Dockerfile
    image: react-ngninx-app:1.0.0
    expose:
      - 3010
    ports:
      - 3010:3000
    container_name: client-test2
    environment:
        - CHOKIDAR_USEPOLLING=true
  
  nginx-load-balancer:
    restart : always
    build :
      context : ./Proxy
      dockerfile : Dockerfile
    image: proxy:1.0.0
    expose:
      - 80
    ports:
      - 80:80