version: '3.8'
services: 
  server1: 
    build: 
      context: ./BE
      dockerfile : Dockerfile
    image: server:latest
    expose:
      - 9192
    ports:
      - 9192:9999
    container_name: server1

  server2: 
    image: server:latest
    expose:
      - 9193
    ports:
      - 9193:9999
    container_name: server2

  server3: 
    image: server:latest
    expose:
      - 9194
    ports:
      - 9194:9999
    container_name: server3

  react-nginx-app:
    stdin_open: true
    build:
      context: ./FE/client
      dockerfile: Dockerfile
    image: client:latest
    expose:
      - 3010
    ports:
      - 3010:3000
    container_name: client-test2
    environment:
        - CHOKIDAR_USEPOLLING=true
  
  nginx-load-balancer:
    restart : always
    build :
      context : ./Proxy
      dockerfile : Dockerfile
    image: proxy:latest
    expose:
      - 5777
    ports:
      - 5777:80